config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :entries, only: [:index, :create]

  get '/all-entries' => 'entries#show'

  get '/entry/:id' => 'entries#location', as: :entry

  root 'entries#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/entry.rb
class Entry < ApplicationRecord
    has_many :locations
    accepts_nested_attributes_for :locations, allow_destroy: true
end

app/models/location.rb
class Location < ApplicationRecord
    belongs_to :entry
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  def index
    @entries = Entry.all
    @new_entry = Entry.new
    @new_entry.locations.build
    @all_entries = Entry.order(created_at: :desc).all
  end

  def show
    @all_entries = Entry.order(created_at: :desc).all
  end

  def location
    @entry = Entry.find(params[:id])
    @locations = @entry.locations
  end

  def create
    @new_entry = Entry.new(entry_params)
    # @new_entry.locations.build(location_params)
    if @new_entry.save
      redirect_to root_path
    end
  end

  private
  def entry_params
    params.require(:entry).permit(
      :state, :lga, :town, :estimated_pop, :radio_stations, :tv_stations,
      :other_comms, :popular_unions, :literacy_level,
      :agent_name, :agent_phone, :daily_withdraw_value,
      :daily_deposit_count, :interest_level, :no_of_locations,
      :alajo_name, :alajo_phone, :alajo_union, :alajo_population, :alajo_avg_age, :alajo_avg_customer,
      :alajo_avg_daily_contr, :alajo_avg_acc_bal,
      locations_attributes: [:location_platform, :location_est, :location_geotag]
    )
  end

  def location_params
    # params.require(:entry).permit(:location_platform, :location_est, :location_geotag)
    params.require(:entry).require(:locations).permit(:location_platform, :location_est, :location_geotag)
  end

end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
  def link_to_add_fields(name, f, model_class, association, cssClass)
    new_object = f.object.class.reflect_on_association(association).klass.new
    fields = f.fields_for(association, new_object, child_index: "new_#{association}") do |builder|
      render(model_class + '/' + association.to_s.singularize + '_fields', section: builder)
    end
    link_to name, '#', class: cssClass, onclick: 'addNewLocationForm(this); return false', data: { association: association, fieldset: fields.to_json }
  end
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/views/entries/_location.html.erb
<div>
<%= f.select :location_platform, options_for_select([['Monniepoint', 'monniepoint'], ['FirstMonie', 'firstmonie'], ['Opay', 'opay'], ['Paga', 'paga'], ['Momo', 'momo'], ['Paycentre', 'paycenter'], ['Other', 'other']], required: true) %>
<%= f.text_field :location_est, class: 'form-control', :placeholder => "Year of establishment", required: true %>
<%= f.text_field :location_geotag, class: 'form-control', id: 'geo-location', :placeholder => "Geotag", required: true %>
</div>

app/views/entries/index.html.erb
    <%= javascript_pack_tag 'index' %>

    <div class="header">
      <div class="container">
        <h1>Monniepoint LSE</h1>
      </div>
    </div>

    <div class="main">
      <div class="content">
        <div class="left-section">
        </div>
        <div class="right-section">
        <%= form_for(@new_entry) do |f| %>
            <div class="form-label-wrap">
              <%= f.label(:state, "Select state", class: "form-label") %>
              <%= f.select :state, 
                  options_for_select([
                      ['Abia', 'Abia'], 
                      ['Adamawa', 'Adamawa'], 
                      ['Akwa Ibom', 'Akwa Ibom'],
                      ['Anambra', 'Anambra'],
                      ['Bauchi', 'Bauchi'],
                      ['Bayelsa', 'Bayelsa'],
                      ['Benue', 'Benue'],
                      ['Borno', 'Borno'],
                      ['Cross River', 'Cross River'],
                      ['Delta', 'Delta'],
                      ['Ebonyi', 'Ebonyi'],
                      ['Edo', 'Edo'],
                      ['Ekiti', 'Ekiti'],
                      ['Enugu', 'Enugu'],
                      ['Gombe', 'Gombe'],
                      ['Imo', 'Imo'],
                      ['Jigawa', 'Jigawa'],
                      ['Kaduna', 'Kaduna'],
                      ['Kano', 'Kano'],
                      ['Katsina', 'Katsina'],
                      ['Kebbi', 'Kebbi'],
                      ['Kogi', 'Kogi'],
                      ['Kwara', 'Kwara'],
                      ['Lagos', 'Lagos'],
                      ['Nassarawa', 'Nassarawa'],
                      ['Niger', 'Niger'],
                      ['Ogun', 'Ogun'],
                      ['Ondo', 'Ondo'],
                      ['Osun', 'Osun'],
                      ['Oyo', 'Oyo'],
                      ['Plateau', 'Plateau'],
                      ['Rivers', 'Rivers'],
                      ['Sokoto', 'Sokoto'],
                      ['Taraba', 'Taraba'],
                      ['Yobe', 'Yobe'],
                      ['Zamfara', 'Zamfara'],
                      ], 
                      required: true) 
              %>
            </div>

            <div class="form-label-wrap">
              <%= f.label(:lga, "LGA", class: "form-label") %>
              <%= f.text_field :lga, class: 'form-control', :placeholder => "Local Govt" %>
            </div>

            <div class="form-label-wrap">
              <%= f.label(:town, "Town", class: "form-label") %>
              <%= f.text_field :town, class: 'form-control', :placeholder => "Town" %>
            </div>

            <div class="form-label-wrap">
              <%= f.label(:estimated_pop, "Estimated Population", class: "form-label") %>
              <%= f.text_field :estimated_pop, class: 'form-control' %>
            </div>

            <div class="form-label-wrap">
            <%= f.label(:radio_stations, "Radio stations", class: "form-label") %>
            <%= f.text_field :radio_stations, class: 'form-control' %>
            </div>

            <div class="form-label-wrap">
            <%= f.label(:tv_stations, "Tv stations", class: "form-label") %>
            <%= f.text_field :tv_stations, class: 'form-control'%>
            </div>

            <div class="form-label-wrap">
            <%= f.label(:other_comms, "Other comms", class: "form-label") %>
            <%= f.text_field :other_comms, class: 'form-control' %>
            </div>

            <div class="form-label-wrap">
              <%= f.label(:popular_unions, "Popular unions", class: "form-label") %>
              <%= f.text_field :popular_unions, class: 'form-control' %>
            </div>

            <div class="form-label-wrap">
              <%= f.label(:literacy_level, "Literacy level", class: "form-label") %>
              <%= f.select :literacy_level, options_for_select([['Level 1', 'Low'], ['Level 2', 'mid'], ['Level 3', 'high']], required: true) %>
            </div>

            <h2>Agent</h2>
            <div class="location-wrap">
                <div class="location-wrap-content">
                    <%= f.label(:agent_name, "Full name", class: "form-label") %>
                    <%= f.text_field :agent_name, class: 'form-control' %>

                    <%= f.label(:agent_phone, "Phone", class: "form-label") %>
                    <%= f.text_field :agent_phone, class: 'form-control', required: true %>

                    <%= f.label(:daily_withdraw_value, "Daily Withdrawal value", class: "form-label") %>
                    <%= f.number_field :daily_withdraw_value, class: 'form-control', required: true %>

                    <%= f.label(:daily_deposit_count, "Daily deposit count", class: "form-label") %>
                    <%= f.number_field :daily_deposit_count, class: 'form-control', required: true %>

                    <%= f.label(:interest_level, "Interest level", class: "form-label") %>
                    <%= f.select :interest_level, options_for_select([['High', 'High'], ['Low', 'Low'], ['Indifferent', 'Indifferent']], required: true) %>

                    <%= f.label(:no_of_locations, "No. of locations", class: "form-label") %>
                    <%= f.number_field :no_of_locations, class: 'form-control', required: true %>
                </div>
            </div>

            <h2>Location</h2>
            <div id="location" class="location-wrap">
                <div class="location-wrap-content">
                  <div id="locations-list">
                    <%= f.fields_for :locations do |section| %>
                      <%= render 'locations/location_fields', section: section %>
                    <% end %>
                  </div>
                </div>
                <%= link_to_add_fields('Add New Location', f, 'locations', :locations, 'location-wrap-btn') %>
            </div>

            <div id="alajo" class="alajo-wrap">
              <div class="location-wrap-btn alajo" id="alajo-btn">Add Alajo</div>
              <div id="alajo-wrap-inner" class="alajo-wrap-inner">
                <h2>Alajo(s)</h2>
                <div class="form-label-wrap">
                  <%= f.label(:alajo_name, "Full name", class: "form-label") %>
                  <%= f.text_field :alajo_name, class: 'form-control' %>
                </div>

                <div class="form-label-wrap">
                  <%= f.label(:alajo_phone, "Phone number", class: "form-label") %>
                  <%= f.text_field :alajo_phone, class: 'form-control', required: true %>
                </div>

                <div class="form-label-wrap">
                  <%= f.label(:alajo_union, "Name of Union", class: "form-label") %>
                  <%= f.text_field :alajo_union, class: 'form-control', required: true %>
                </div>

                <div class="form-wrap">
                  <div class="form-label-wrap half-width">
                    <%= f.label(:alajo_population, "Population of union", class: "form-label") %>
                    <%= f.text_field :alajo_population, class: 'form-control', required: true %>
                  </div>

                  <div class="form-label-wrap half-width">
                    <%= f.label(:alajo_avg_age, "Average age in union", class: "form-label") %>
                    <%= f.text_field :alajo_avg_age, class: 'form-control', required: true %>
                  </div>
                </div>

                <div class="form-label-wrap">
                  <%= f.label(:alajo_avg_customer, "Average customer", class: "form-label") %>
                  <%= f.text_field :alajo_avg_customer, class: 'form-control', required: true %>
                </div>

                <div class="form-label-wrap">
                  <%= f.label(:alajo_avg_daily_contr, "Average daily contribution", class: "form-label") %>
                  <%= f.text_field :alajo_avg_daily_contr, class: 'form-control', required: true %>
                </div>

                <div class="form-label-wrap">
                  <%= f.label(:alajo_avg_acc_bal, "Average account balance", class: "form-label") %>
                  <%= f.text_field :alajo_avg_acc_bal, class: 'form-control', required: true %>
                </div>
              </div>
            </div>
            <%= f.submit "Submit", :class => "btn"  %>
        <% end %>
        </div>

      </div>
    </div>

app/views/entries/location.html.erb
<div>
    <h1>Location data</h1>
    <table id="customers">
    <tr>
        <th>S/N</th>
        <th>Platform</th>
        <th>Date of establishment</th>
        <th>Geotag</th>
    </tr>
    <% @locations.each do |l| %>
        <tr>
            <td><%= l.id %></td>
            <td><%= l.location_platform %></td>
            <td><%= l.location_est %></td>
            <td><%= l.location_geotag %></td>
        </tr>
    <% end %>
    
    </table>
</div>

app/views/entries/show.html.erb
<table id="customers">
  <h1>Entry</h1>
  <tr>
    <th>Link</th>
    <th>S/N</th>
    <th>State</th>
    <th>LGA</th>
    <th>Town</th>
    <th>Estimated population</th>
    <th>Radio stations</th>
    <th>Tv Stations</th>
    <th>Other comms</th>
    <th>Popular unions</th>
    <th>Literacy level</th>
  </tr>
  <% @all_entries.each do |p| %>
    <tr>
        <td><%= link_to "Location", entry_path(p)%></td>
        <td><%= p.id %></td>
        <td><%= p.state %></td>
        <td><%= p.lga %></td>
        <td><%= p.town %></td>
        <td><%= p.estimated_pop %></td>
        <td><%= p.radio_stations %></td>
        <td><%= p.tv_stations %></td>
        <td><%= p.other_comms %></td>
        <td><%= p.popular_unions %></td>
        <td><%= p.literacy_level %></td>
    </tr>
  <% end %>
  
</table>
<h1>Agent</h1>
<table id="customers">
  <tr>
    <th>S/N</th>
    <th>Agent name</th>
    <th>Agent phone</th>
    <th>Daily withdraw value</th>
    <th>Daily deposit count</th>
    <th>Interest level</th>
    <th>Number of locations</th>
  </tr>
  <% @all_entries.each do |p| %>
    <tr>
        <td><%= p.id %></td>
        <td><%= p.agent_name %></td>
        <td><%= p.agent_phone %></td>
        <td><%= p.daily_withdraw_value %></td>
        <td><%= p.daily_deposit_count %></td>
        <td><%= p.interest_level %></td>
        <td><%= p.no_of_locations %></td>
    </tr>
  <% end %>
</table>


<h1>Alajo</h1>
<table id="customers">
  <tr>
    <th>S/N</th>
    <th>Full name</th>
    <th>Phone no.</th>
    <th>Prime location</th>
    <th>Number of locations</th>
    <th>Union</th>
    <th>Population</th>
    <th>Average age</th>
    <th>Average customer age</th>
    <th>Average daily contribution</th>
    <th>Average account balance</th>
  </tr>
  <% @all_entries.each do |p| %>
    <tr>
        <td><%= p.id %></td>
        <td><%= p.alajo_name %></td>
        <td><%= p.alajo_phone %></td>
        <td><%= p.alajo_prime_location %></td>
        <td><%= p.alajo_no_of_locations %></td>
        <td><%= p.alajo_union %></td>
        <td><%= p.alajo_population %></td>
        <td><%= p.alajo_avg_age %></td>
        <td><%= p.alajo_avg_customer %></td>
        <td><%= p.alajo_avg_daily_contr %></td>
        <td><%= p.alajo_avg_acc_bal %></td>
    </tr>
  <% end %>
  
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MonniepointLse</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/locations/_location_fields.html.erb
<%= section.label(:location_platform, "Platform used", class: "form-label") %>
<%= section.select :location_platform, options_for_select([['Monniepoint', 'monniepoint'], ['FirstMonie', 'firstmonie'], ['Opay', 'opay'], ['Paga', 'paga'], ['Momo', 'momo'], ['Paycentre', 'paycenter'], ['Other', 'other']], required: true) %>

<%= section.label(:location_est, "Year of establishment", class: "form-label") %>
<%= section.text_field :location_est, class: 'form-control', required: true %>

<%= section.label(:location_geotag, "Geotag", class: "form-label") %>
<%= section.text_field :location_geotag, class: 'form-control geotag', id: 'geo-location' %>